### ISSUE TITLE
Implement restorative / buff item use

### ISSUE THREAD

**Issue by MManifesto** [lbaribeau/los-helper#14]
Using items.  Logic should be included to keep a minimum of each item (steel and chalice and restoratives) but otherwise use them up when needed.

**Comment by lbaribeau** [comment]
This is working well enough to close the issue.  As with many issues though we could go farther with it.
Done: using restoratives when low in health
keeping a minimum number of steel bottles
using restoratives to free up weight (now rings are a bigger issue,) while saving 5 scarlet potions
determining when a larger restorative is preferred
Steel bottles get used when inventory is full

Could do: using extra restoratives to rest more efficiently or to avoid resting
detecting high mob dps to start spamming restoratives earlier (when desired)
add crafting restoratives to Druid grind AI
keep minimum number of silver chalices or milky potions
Use/buy silver chalices or milky potions (separate issue)
Routinely using steel bottles

Also, we should make are issues small in scope.  "Using items" is broad and may never be satisfactorily "completed."  Buffs and restoratives can be separate.
